# Generated by Django 3.0.5 on 2020-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anoyumus', max_length=50)),
                ('phone', models.IntegerField(default='0', max_length=12)),
                ('purpose', models.CharField(max_length=300)),
                ('amount', models.IntegerField(default='0', max_length=10)),
            ],
        ),
    ]
