# Generated by Django 3.0.5 on 2020-05-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='main/slider')),
            ],
        ),
        migrations.CreateModel(
            name='postrequest',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=70)),
                ('date', models.DateField(default='', max_length=70)),
                ('time', models.TimeField(default='', max_length=70)),
                ('poster', models.ImageField(upload_to='main/slider')),
                ('desc', models.CharField(max_length=300)),
                ('verification', models.BooleanField()),
                ('category', models.CharField(choices=[('mehfil', 'Mehfil'), ('majlis', 'Majlis'), ('others', 'Others')], default='others', max_length=50)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city')),
            ],
        ),
    ]
