# Generated by Django 3.0.5 on 2020-05-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaiyar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shaiyarname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='main/slider')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.postrequest')),
            ],
        ),
    ]
