# Generated by Django 3.0.5 on 2020-05-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shaiyar'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacter', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='postrequest',
            name='attendences',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='organiser',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='taam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='poster',
            field=models.ImageField(default='', upload_to='main/slider'),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shaiyar',
            name='photo',
            field=models.ImageField(default='', upload_to='main/slider'),
        ),
        migrations.CreateModel(
            name='mehfildetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nizamat', models.CharField(max_length=50)),
                ('nizamimage', models.ImageField(default='', upload_to='main/slider')),
                ('sadarat', models.ImageField(default='', upload_to='main/slider')),
                ('mehfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.postrequest')),
            ],
        ),
    ]
