# Generated by Django 3.0.5 on 2020-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200601_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Maaz', max_length=50, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
